const data = {
  locations: [
    {
      name: 'Starbucks Seijo Shop',
      slug: 'starbucks-seijo',
      imageUrl: '/static/coffee.jpg',
      address: '2 Chome−40−25 パレブラン成城',
      city: 'Setagaya City',
      neighborhood: 'Seijo',
      prefecture: 'Tokyo',
      postalCode: '〒157-0066',
      country: 'Japan',
      cc: 'JPN',
      rating: 3.6,
    },
    {
      name: 'Doutor',
      slug: 'doutor-seijo',
      imageUrl: '/static/coffee.jpg',
      address: '6 Chome−9−1 五和ビル １Ｆ',
      city: 'Setagaya City',
      neighborhood: 'Seijo',
      prefecture: 'Tokyo',
      postalCode: '〒157-0066',
      country: 'Japan',
      cc: 'JPN',
      rating: 3.3,
    },
    {
      name: 'Ueshima Coffee Seijo Shop',
      slug: 'ueshima-coffee-seijo',
      imageUrl: '/static/coffee.jpg',
      address: '2 Chome−39−7 すみれビル',
      city: 'Setagaya City',
      neighborhood: 'Seijo',
      prefecture: 'Tokyo',
      postalCode: '〒157-0066',
      country: 'Japan',
      cc: 'JPN',
      rating: 3.6,
    },
    {
      name: 'Dean & Deluca Seijo',
      slug: 'dean-deluca-seijo',
      imageUrl: '/static/coffee.jpg',
      address: '6 Chome−5−34 成城コルティ 1F',
      city: 'Setagaya City',
      neighborhood: 'Seijo',
      prefecture: 'Tokyo',
      postalCode: '〒157-0066',
      country: 'Japan',
      cc: 'JPN',
      rating: 3.5,
    },
    {
      name: 'Sakura Cafe',
      slug: 'sakura-cafe-seijo',
      imageUrl: '/static/coffee.jpg',
      address: '6 Chome-2-1',
      city: 'Setagaya City',
      neighborhood: 'Seijo',
      prefecture: 'Tokyo',
      postalCode: '〒157-0066',
      country: 'Japan',
      cc: 'JPN',
      rating: 5,
    },
    {
      name: 'Cafe Beulmans',
      slug: 'cafe-beulmans-seijo',
      imageUrl: '/static/coffee.jpg',
      address: '6 Chome−16−5 カサローザ成城2F',
      city: 'Setagaya City',
      neighborhood: 'Seijo',
      prefecture: 'Tokyo',
      postalCode: '〒157-0066',
      country: 'Japan',
      cc: 'JPN',
      rating: 5,
    },
    {
      name: 'Soreiyu',
      slug: 'soreiyu-seijo',
      imageUrl: '/static/coffee.jpg',
      address: '2 Chome−40−3 ソレイユ',
      city: 'Setagaya City',
      neighborhood: 'Seijo',
      prefecture: 'Tokyo',
      postalCode: '〒157-0066',
      country: 'Japan',
      cc: 'JPN',
      rating: 4.3,
    },
  ],
};

export default data;
